import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets:['latin'],
  weight:['100','200','300','400','500','600','700','800','900'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Path must match file in /public
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png", // Apple touch icon (optional)
    other: {
      rel: "icon",
      url: "/icon.png", // Alternative favicon (PNG/SVG)
    },
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={`${poppins.variable} font-poppins antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
